const samples = {
  mockSamples: true,
  count: 34,
  results: [
    {
      facebook_posts: [],
      brand: null,
      show_id: 17,
      buzz_id: null,
      tips_and_ratings_enabled: true,
      description:
        'Aguachile is traditionally made with shrimp, but since 2023 is going to be all about mushrooms, we decided to try it out. King oyster mushrooms have a meaty texture and pair well with the herby, citrusy marinade.',
      credits: [
        {
          name: 'Ivanna Lopez Guajardo',
          type: 'internal',
        },
      ],
      instructions: [
        {
          end_time: 0,
          temperature: null,
          id: 74232,
          position: 1,
          display_text:
            'Make the aguachile: On a mandoline, thinly slice the mushroom stems crosswise into rounds (reserve the mushroom caps for another use). Transfer to a bowl or deep container. Thinly slice the red onion on the mandoline and add to the bowl with the mushrooms.',
          start_time: 0,
          appliance: null,
        },
        {
          start_time: 3833,
          appliance: null,
          end_time: 11166,
          temperature: null,
          id: 74233,
          position: 2,
          display_text:
            'In a blender, combine the cilantro, cucumber, serrano, jalapeño, garlic, lime juice, vinegar, and salt and blend on high speed until smooth, about 30 seconds.',
        },
        {
          position: 3,
          display_text:
            'Pour the marinade over the mushrooms and onion and stir to coat completely. Let sit for 5–10 minutes.',
          start_time: 11000,
          appliance: null,
          end_time: 12666,
          temperature: null,
          id: 74234,
        },
        {
          end_time: 0,
          temperature: null,
          id: 74235,
          position: 4,
          display_text:
            'While the mushrooms are marinating, prepare the garnishes: using a mandoline, thinly slice the cucumber into rounds. Thinly slice the red onion.',
          start_time: 0,
          appliance: null,
        },
        {
          appliance: null,
          end_time: 18166,
          temperature: null,
          id: 74236,
          position: 5,
          display_text:
            'To serve, arrange the sliced cucumber on a serving plate. Spoon the marinated mushrooms and onion on top, along with some of the marinade. Garnish with the thinly sliced red onion, cilantro, and black pepper. Serve immediately.',
          start_time: 14000,
        },
        {
          start_time: 19666,
          appliance: null,
          end_time: 21000,
          temperature: null,
          id: 74237,
          position: 6,
          display_text: 'Enjoy!',
        },
      ],
      promotion: 'full',
      topics: [
        {
          name: 'Best Vegetarian',
          slug: 'best-vegetarian',
        },
        {
          slug: 'healthy',
          name: 'Healthy Eating',
        },
        {
          name: 'Low Carb Meals',
          slug: 'low-carb-meals',
        },
        {
          name: 'Vegan',
          slug: 'vegan',
        },
        {
          name: 'Mexican',
          slug: 'mexican',
        },
      ],
      price: {
        consumption_total: 500,
        consumption_portion: 250,
        total: 950,
        updated_at: '2023-01-26T06:34:10+01:00',
        portion: 450,
      },
      id: 8598,
      slug: 'king-oyster-mushroom-aguachile',
      is_shoppable: true,
      user_ratings: {
        count_positive: 5,
        score: 1,
        count_negative: 0,
      },
      is_one_top: false,
      renditions: [
        {
          poster_url:
            'https://img.buzzfeed.com/video-transcoder-prod/output/269974/square_720/1674000953_00001.png',
          url: 'https://vid.tasty.co/output/269974/square_720/1674000953',
          minimum_bit_rate: null,
          maximum_bit_rate: null,
          width: 404,
          name: 'mp4_404x720',
          container: 'mp4',
          file_size: 4746926,
          duration: 21272,
          bit_rate: 1786,
          content_type: 'video/mp4',
          aspect: 'portrait',
          height: 720,
        },
        {
          content_type: 'video/mp4',
          width: 180,
          height: 320,
          poster_url:
            'https://img.buzzfeed.com/video-transcoder-prod/output/269974/square_320/1674000953_00001.png',
          duration: 21272,
          url: 'https://vid.tasty.co/output/269974/square_320/1674000953',
          bit_rate: 629,
          aspect: 'portrait',
          minimum_bit_rate: null,
          name: 'mp4_180x320',
          maximum_bit_rate: null,
          container: 'mp4',
          file_size: 1672437,
        },
        {
          duration: 21272,
          width: 404,
          minimum_bit_rate: null,
          name: 'mp4_404x720',
          container: 'mp4',
          poster_url:
            'https://img.buzzfeed.com/video-transcoder-prod/output/269974/landscape_720/1674000953_00001.png',
          file_size: 4744438,
          url: 'https://vid.tasty.co/output/269974/landscape_720/1674000953',
          height: 720,
          bit_rate: 1785,
          content_type: 'video/mp4',
          aspect: 'portrait',
          maximum_bit_rate: null,
        },
        {
          minimum_bit_rate: null,
          height: 480,
          poster_url:
            'https://img.buzzfeed.com/video-transcoder-prod/output/269974/landscape_480/1674000953_00001.png',
          duration: 21272,
          aspect: 'portrait',
          bit_rate: 1024,
          content_type: 'video/mp4',
          width: 270,
          name: 'mp4_270x480',
          maximum_bit_rate: null,
          container: 'mp4',
          file_size: 2722100,
          url: 'https://vid.tasty.co/output/269974/landscape_480/1674000953',
        },
        {
          name: 'low',
          maximum_bit_rate: 2850,
          container: 'ts',
          file_size: null,
          duration: 21313,
          bit_rate: null,
          content_type: 'application/vnd.apple.mpegurl',
          height: 1080,
          poster_url:
            'https://img.buzzfeed.com/video-transcoder-prod/output/269974/1445289064805-h2exzu/1674000953_00001.png',
          url: 'https://vid.tasty.co/output/269974/hls24_1674000953.m3u8',
          aspect: 'portrait',
          width: 608,
          minimum_bit_rate: 277,
        },
      ],
      yields: 'Servings: 2',
      canonical_id: 'recipe:8598',
      video_id: 178359,
      compilations: [],
      video_url: 'https://vid.tasty.co/output/269974/hls24_1674000953.m3u8',
      updated_at: 1674157711,
      approved_at: 1674060191,
      servings_noun_plural: 'servings',
      seo_title: 'Mushroom Aguachile',
      cook_time_minutes: 0,
      seo_path: null,
      nutrition: {
        updated_at: '2023-01-19T07:01:09+01:00',
        protein: 3,
        fat: 0,
        calories: 100,
        sugar: 8,
        carbohydrates: 25,
        fiber: 28,
      },
      num_servings: 2,
      show: {
        name: 'Tasty',
        id: 17,
      },
      draft_status: 'published',
      inspired_by_url: null,
      thumbnail_alt_text: '',
      total_time_minutes: 20,
      country: 'US',
      total_time_tier: {
        tier: 'under_30_minutes',
        display_tier: 'Under 30 minutes',
      },
      servings_noun_singular: 'serving',
      prep_time_minutes: 15,
      sections: [
        {
          components: [
            {
              id: 98469,
              position: 1,
              measurements: [
                {
                  unit: {
                    system: 'none',
                    name: '',
                    display_plural: '',
                    display_singular: '',
                    abbreviation: '',
                  },
                  quantity: '4',
                  id: 720141,
                },
              ],
              raw_text: '4 king oyster mushroom stems',
              extra_comment: '',
              ingredient: {
                display_singular: 'king oyster mushroom',
                updated_at: 1583947203,
                name: 'king oyster mushrooms',
                created_at: 1583947203,
                display_plural: 'king oyster mushrooms',
                id: 6286,
              },
            },
            {
              raw_text: '¼ medium red onion',
              extra_comment: '',
              ingredient: {
                display_plural: 'medium red onions',
                id: 148,
                display_singular: 'medium red onion',
                updated_at: 1509035283,
                name: 'medium red onion',
                created_at: 1493906093,
              },
              id: 98470,
              position: 2,
              measurements: [
                {
                  quantity: '¼',
                  id: 720140,
                  unit: {
                    display_singular: '',
                    abbreviation: '',
                    system: 'none',
                    name: '',
                    display_plural: '',
                  },
                },
              ],
            },
            {
              measurements: [
                {
                  unit: {
                    system: 'none',
                    name: 'bunch',
                    display_plural: 'bunches',
                    display_singular: 'bunch',
                    abbreviation: 'bunch',
                  },
                  quantity: '½',
                  id: 720142,
                },
              ],
              raw_text: '½ bunch fresh cilantro',
              extra_comment: '',
              ingredient: {
                updated_at: 1509035266,
                name: 'fresh cilantro',
                created_at: 1494974463,
                display_plural: 'fresh cilantros',
                id: 372,
                display_singular: 'fresh cilantro',
              },
              id: 98471,
              position: 3,
            },
            {
              ingredient: {
                created_at: 1497125172,
                display_plural: 'large cucumbers',
                id: 1808,
                display_singular: 'large cucumber',
                updated_at: 1509035164,
                name: 'large cucumber',
              },
              id: 98472,
              position: 4,
              measurements: [
                {
                  id: 720150,
                  unit: {
                    system: 'none',
                    name: '',
                    display_plural: '',
                    display_singular: '',
                    abbreviation: '',
                  },
                  quantity: '½',
                },
              ],
              raw_text: '½ large cucumber, halved lengthwise and seeds removed',
              extra_comment: 'halved lengthwise and seeds removed',
            },
            {
              position: 5,
              measurements: [
                {
                  unit: {
                    name: '',
                    display_plural: '',
                    display_singular: '',
                    abbreviation: '',
                    system: 'none',
                  },
                  quantity: '1',
                  id: 720148,
                },
              ],
              raw_text: '1 serrano pepper, stemmed',
              extra_comment: 'stemmed',
              ingredient: {
                display_singular: 'serrano pepper',
                updated_at: 1509035216,
                name: 'serrano pepper',
                created_at: 1496174028,
                display_plural: 'serrano peppers',
                id: 983,
              },
              id: 98473,
            },
            {
              extra_comment: 'stemmed',
              ingredient: {
                id: 596,
                display_singular: 'jalapeño pepper',
                updated_at: 1509035248,
                name: 'jalapeño pepper',
                created_at: 1495418630,
                display_plural: 'jalapeño peppers',
              },
              id: 98474,
              position: 6,
              measurements: [
                {
                  unit: {
                    system: 'none',
                    name: '',
                    display_plural: '',
                    display_singular: '',
                    abbreviation: '',
                  },
                  quantity: '1',
                  id: 720153,
                },
              ],
              raw_text: '1 jalapeño pepper, stemmed',
            },
            {
              id: 98475,
              position: 7,
              measurements: [
                {
                  unit: {
                    name: 'large clove',
                    display_plural: 'large cloves',
                    display_singular: 'large clove',
                    abbreviation: 'large clove',
                    system: 'none',
                  },
                  quantity: '2',
                  id: 720144,
                },
              ],
              raw_text: '2 large garlic cloves',
              extra_comment: '',
              ingredient: {
                updated_at: 1509035285,
                name: 'garlic',
                created_at: 1493744766,
                display_plural: 'garlics',
                id: 95,
                display_singular: 'garlic',
              },
            },
            {
              raw_text: '1 cup fresh lime juice',
              extra_comment: '',
              ingredient: {
                display_singular: 'fresh lime juice',
                updated_at: 1509035108,
                name: 'fresh lime juice',
                created_at: 1501643053,
                display_plural: 'fresh lime juices',
                id: 2799,
              },
              id: 98476,
              position: 8,
              measurements: [
                {
                  unit: {
                    abbreviation: 'c',
                    system: 'imperial',
                    name: 'cup',
                    display_plural: 'cups',
                    display_singular: 'cup',
                  },
                  quantity: '1',
                  id: 720149,
                },
                {
                  unit: {
                    abbreviation: 'mL',
                    system: 'metric',
                    name: 'milliliter',
                    display_plural: 'mL',
                    display_singular: 'mL',
                  },
                  quantity: '240',
                  id: 720145,
                },
              ],
            },
            {
              extra_comment: '',
              ingredient: {
                updated_at: 1509035252,
                name: 'distilled white vinegar',
                created_at: 1495235671,
                display_plural: 'distilled white vinegars',
                id: 544,
                display_singular: 'distilled white vinegar',
              },
              id: 98477,
              position: 9,
              measurements: [
                {
                  quantity: '1',
                  id: 720143,
                  unit: {
                    system: 'imperial',
                    name: 'tablespoon',
                    display_plural: 'tablespoons',
                    display_singular: 'tablespoon',
                    abbreviation: 'tbsp',
                  },
                },
              ],
              raw_text: '1 tablespoon distilled white vinegar',
            },
            {
              raw_text: '1 teaspoon kosher salt',
              extra_comment: '',
              ingredient: {
                name: 'kosher salt',
                created_at: 1493307153,
                display_plural: 'kosher salts',
                id: 11,
                display_singular: 'kosher salt',
                updated_at: 1509035289,
              },
              id: 98478,
              position: 10,
              measurements: [
                {
                  unit: {
                    display_plural: 'teaspoons',
                    display_singular: 'teaspoon',
                    abbreviation: 'tsp',
                    system: 'imperial',
                    name: 'teaspoon',
                  },
                  quantity: '1',
                  id: 720146,
                },
              ],
            },
          ],
          name: null,
          position: 1,
        },
        {
          components: [
            {
              id: 98480,
              position: 12,
              measurements: [
                {
                  unit: {
                    system: 'none',
                    name: '',
                    display_plural: '',
                    display_singular: '',
                    abbreviation: '',
                  },
                  quantity: '½',
                  id: 720147,
                },
              ],
              raw_text: '½ large cucumber',
              extra_comment: '',
              ingredient: {
                id: 1808,
                display_singular: 'large cucumber',
                updated_at: 1509035164,
                name: 'large cucumber',
                created_at: 1497125172,
                display_plural: 'large cucumbers',
              },
            },
            {
              raw_text: '⅛ medium red onion',
              extra_comment: '',
              ingredient: {
                created_at: 1493906093,
                display_plural: 'medium red onions',
                id: 148,
                display_singular: 'medium red onion',
                updated_at: 1509035283,
                name: 'medium red onion',
              },
              id: 98481,
              position: 13,
              measurements: [
                {
                  unit: {
                    system: 'none',
                    name: '',
                    display_plural: '',
                    display_singular: '',
                    abbreviation: '',
                  },
                  quantity: '½',
                  id: 720152,
                },
              ],
            },
            {
              measurements: [
                {
                  unit: {
                    display_plural: 'tablespoons',
                    display_singular: 'tablespoon',
                    abbreviation: 'tbsp',
                    system: 'imperial',
                    name: 'tablespoon',
                  },
                  quantity: '1',
                  id: 720154,
                },
              ],
              raw_text: '1 tablespoon chopped fresh cilantro',
              extra_comment: 'chopped',
              ingredient: {
                updated_at: 1509035266,
                name: 'fresh cilantro',
                created_at: 1494974463,
                display_plural: 'fresh cilantros',
                id: 372,
                display_singular: 'fresh cilantro',
              },
              id: 98482,
              position: 14,
            },
            {
              position: 15,
              measurements: [
                {
                  unit: {
                    system: 'none',
                    name: '',
                    display_plural: '',
                    display_singular: '',
                    abbreviation: '',
                  },
                  quantity: '0',
                  id: 720151,
                },
              ],
              raw_text: 'Freshly ground black pepper, to taste',
              extra_comment: 'to taste',
              ingredient: {
                display_plural: 'freshly ground black peppers',
                id: 166,
                display_singular: 'freshly ground black pepper',
                updated_at: 1509035282,
                name: 'freshly ground black pepper',
                created_at: 1493925438,
              },
              id: 98483,
            },
          ],
          name: 'For Garnish',
          position: 2,
        },
      ],
      tags: [
        {
          id: 64457,
          display_name: 'Mexican',
          type: 'cuisine',
          name: 'mexican',
        },
        {
          display_name: 'Low-Carb',
          type: 'healthy',
          name: 'low_carb',
          id: 64467,
        },
        {
          id: 8091916,
          display_name: 'Low-Calorie',
          type: 'healthy',
          name: 'low_calorie',
        },
        {
          name: 'vegan',
          id: 64468,
          display_name: 'Vegan',
          type: 'dietary',
        },
        {
          name: 'appetizers',
          id: 64481,
          display_name: 'Appetizers',
          type: 'meal',
        },
        {
          type: 'healthy',
          name: 'low_fat',
          id: 8091919,
          display_name: 'Low-Fat',
        },
        {
          name: 'under_30_minutes',
          id: 64472,
          display_name: 'Under 30 Minutes',
          type: 'difficulty',
        },
        {
          name: 'healthy',
          id: 64466,
          display_name: 'Healthy',
          type: 'dietary',
        },
        {
          type: 'dietary',
          name: 'vegetarian',
          id: 64469,
          display_name: 'Vegetarian',
        },
        {
          type: 'difficulty',
          name: 'under_45_minutes',
          id: 8091747,
          display_name: 'Under 45 Minutes',
        },
        {
          name: 'under_1_hour',
          id: 8091748,
          display_name: 'Under 1 Hour',
          type: 'difficulty',
        },
        {
          display_name: 'Dairy-Free',
          type: 'dietary',
          name: 'dairy_free',
          id: 64463,
        },
        {
          id: 3801552,
          display_name: 'Pescatarian',
          type: 'dietary',
          name: 'pescatarian',
        },
      ],
      created_at: 1674001189,
      nutrition_visibility: 'auto',
      brand_id: null,
      name: 'King Oyster Mushroom Aguachile',
      original_video_url:
        'https://s3.amazonaws.com/video-api-prod/assets/9b6c594b210742b598c0d114ce39fcc3/BFV99172_MushroomAguachile_9x16.mp4',
      language: 'eng',
      aspect_ratio: '9:16',
      thumbnail_url:
        'https://img.buzzfeed.com/thumbnailer-prod-us-east-1/2d621962e80649cb990b8adca3cf2df9/BFV99172_MushroomAguachile_9x16.jpg',
      beauty_url: null,
      video_ad_content: 'none',
      keywords: '',
    },
    {
      total_time_tier: {
        tier: 'under_30_minutes',
        display_tier: 'Under 30 minutes',
      },
      video_id: 167170,
      user_ratings: {
        count_positive: 53,
        score: 0.898305,
        count_negative: 6,
      },
      prep_time_minutes: 10,
      tips_and_ratings_enabled: true,
      inspired_by_url: null,
      created_at: 1664482587,
      updated_at: 1664807090,
      credits: [
        {
          name: 'Murad Yasin',
          type: 'internal',
        },
      ],
      seo_title: 'Eat Your Feed Fest Pizza Recipe & Ticket Giveaway ',
      slug: 'eat-your-feed-fest-pizza',
      compilations: [],
      beauty_url: null,
      is_shoppable: false,
      instructions: [
        {
          position: 1,
          display_text: 'Tap the “I made this!” button on this recipe.',
          start_time: 0,
          appliance: null,
          end_time: 0,
          temperature: null,
          id: 73374,
        },
        {
          position: 2,
          display_text:
            'Leave a comment letting us know which Tasty recipe you’d like to enjoy at Eat Your Feed Fest or why you love Tasty with the hashtag #EatYourFeedFest.',
          start_time: 0,
          appliance: null,
          end_time: 0,
          temperature: null,
          id: 73375,
        },
        {
          start_time: 0,
          appliance: null,
          end_time: 0,
          temperature: null,
          id: 73376,
          position: 3,
          display_text:
            'Let us know how to contact you using the official entry form (link is located in the tip section).',
        },
        {
          id: 73377,
          position: 4,
          display_text: 'Mark your calendars for November 19 and 20.',
          start_time: 0,
          appliance: null,
          end_time: 0,
          temperature: null,
        },
        {
          position: 5,
          display_text: 'Keep an eye out for our ticket winner announcement by November 10, 2022.',
          start_time: 0,
          appliance: null,
          end_time: 0,
          temperature: null,
          id: 73378,
        },
        {
          start_time: 0,
          appliance: null,
          end_time: 0,
          temperature: null,
          id: 73379,
          position: 6,
          display_text:
            "Enjoy live cooking demos hosted by your favorite creators, try some of Tasty's most popular recipes, and eat your way through some of LA's most iconic restaurants and food trucks!",
        },
        {
          id: 73380,
          position: 7,
          display_text: 'Have fun!',
          start_time: 0,
          appliance: null,
          end_time: 0,
          temperature: null,
        },
      ],
      keywords:
        'complexcon, cooking demos, eat your feed fest, food, local eats, long beach, pizza, recipe, tasty, ticket giveaway, viral',
      price: {
        updated_at: '2023-01-26T06:33:47+01:00',
        portion: 0,
        consumption_total: 0,
        consumption_portion: 0,
        total: 0,
      },
      id: 8494,
      topics: [
        {
          slug: '5-ingredients-or-less',
          name: '5 Ingredients or Less',
        },
        {
          name: 'Best Vegetarian',
          slug: 'best-vegetarian',
        },
        {
          name: 'Easy Dinner',
          slug: 'easy-dinner',
        },
        {
          name: 'Healthy Eating',
          slug: 'healthy',
        },
        {
          name: 'Keto',
          slug: 'keto',
        },
        {
          name: 'Vegan',
          slug: 'vegan',
        },
        {
          name: 'Lunch',
          slug: 'lunch',
        },
        {
          name: 'Dinner',
          slug: 'dinner',
        },
      ],
      yields: 'Servings: 8',
      canonical_id: 'recipe:8494',
      video_ad_content: 'none',
      facebook_posts: [],
      nutrition: {},
      show: {
        id: 17,
        name: 'Tasty',
      },
      renditions: [
        {
          width: 404,
          name: 'mp4_404x720',
          height: 720,
          container: 'mp4',
          duration: 24381,
          aspect: 'portrait',
          bit_rate: 1995,
          content_type: 'video/mp4',
          minimum_bit_rate: null,
          maximum_bit_rate: null,
          poster_url:
            'https://img.buzzfeed.com/video-transcoder-prod/output/255984/square_720/1664467917_00001.png',
          file_size: 6079406,
          url: 'https://vid.tasty.co/output/255984/square_720/1664467917',
        },
        {
          height: 320,
          poster_url:
            'https://img.buzzfeed.com/video-transcoder-prod/output/255984/square_320/1664467917_00001.png',
          file_size: 2174791,
          url: 'https://vid.tasty.co/output/255984/square_320/1664467917',
          duration: 24381,
          aspect: 'portrait',
          minimum_bit_rate: null,
          name: 'mp4_180x320',
          container: 'mp4',
          bit_rate: 714,
          content_type: 'video/mp4',
          width: 180,
          maximum_bit_rate: null,
        },
        {
          bit_rate: 1993,
          aspect: 'portrait',
          maximum_bit_rate: null,
          height: 720,
          duration: 24381,
          content_type: 'video/mp4',
          width: 404,
          minimum_bit_rate: null,
          container: 'mp4',
          poster_url:
            'https://img.buzzfeed.com/video-transcoder-prod/output/255984/landscape_720/1664467917_00001.png',
          file_size: 6072532,
          url: 'https://vid.tasty.co/output/255984/landscape_720/1664467917',
          name: 'mp4_404x720',
        },
        {
          duration: 24381,
          aspect: 'portrait',
          minimum_bit_rate: null,
          name: 'mp4_270x480',
          maximum_bit_rate: null,
          height: 480,
          file_size: 3535557,
          poster_url:
            'https://img.buzzfeed.com/video-transcoder-prod/output/255984/landscape_480/1664467917_00001.png',
          url: 'https://vid.tasty.co/output/255984/landscape_480/1664467917',
          bit_rate: 1161,
          content_type: 'video/mp4',
          width: 270,
          container: 'mp4',
        },
        {
          content_type: 'application/vnd.apple.mpegurl',
          aspect: 'portrait',
          width: 608,
          minimum_bit_rate: 278,
          maximum_bit_rate: 3100,
          container: 'ts',
          url: 'https://vid.tasty.co/output/255984/hls24_1664467917.m3u8',
          duration: 24400,
          bit_rate: null,
          name: 'low',
          height: 1080,
          poster_url:
            'https://img.buzzfeed.com/video-transcoder-prod/output/255984/1445289064805-h2exzu/1664467917_00001.png',
          file_size: null,
        },
      ],
      is_one_top: false,
      original_video_url:
        'https://s3.amazonaws.com/video-api-prod/assets/6798bdd51a96437ea04bf91de3a54fd5/EYFF_RECIPE_PROMO_V05.mp4',
      show_id: 17,
      name: 'Eat Your Feed Fest Pizza',
      num_servings: 8,
      video_url: 'https://vid.tasty.co/output/255984/hls24_1664467917.m3u8',
      description:
        'Join Tasty & First We Feast for Eat Your Feed Fest, our first-ever food festival, November 19 and 20, 2022 in Long Beach, California! Want to attend the fest as our guest? Leave a comment on this recipe letting us know what you’d like to try at Eat Your Feed Fest and fill out our <a href="https://docs.google.com/forms/d/e/1FAIpQLSeJkPFqODH2GRe_gb_2Bs0MuuMFLKFRjiWmmctlX6UyeJXNEg/viewform?usp=sf_link">official entry form</a>. The winner will receive two General Admission 2-Day Tickets to ComplexCon. Winners will be selected at random and notified by November 10, 2022.',
      thumbnail_url:
        'https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/402248.jpg',
      thumbnail_alt_text: '',
      total_time_minutes: 20,
      nutrition_visibility: 'auto',
      brand_id: null,
      buzz_id: null,
      aspect_ratio: '9:16',
      servings_noun_plural: 'servings',
      cook_time_minutes: 10,
      promotion: 'full',
      brand: null,
      servings_noun_singular: 'serving',
      tags: [
        {
          name: '5_ingredients_or_less',
          id: 64470,
          display_name: '5 Ingredients or Less',
          type: 'difficulty',
        },
        {
          name: 'easy',
          id: 64471,
          display_name: 'Easy',
          type: 'difficulty',
        },
        {
          display_name: 'Under 1 Hour',
          type: 'difficulty',
          name: 'under_1_hour',
          id: 8091748,
        },
        {
          name: 'under_15_minutes',
          id: 8091744,
          display_name: 'Under 15 Minutes',
          type: 'difficulty',
        },
        {
          id: 64472,
          display_name: 'Under 30 Minutes',
          type: 'difficulty',
          name: 'under_30_minutes',
        },
        {
          name: 'under_45_minutes',
          id: 8091747,
          display_name: 'Under 45 Minutes',
          type: 'difficulty',
        },
        {
          name: 'dinner',
          id: 64486,
          display_name: 'Dinner',
          type: 'meal',
        },
        {
          display_name: 'Lunch',
          type: 'meal',
          name: 'lunch',
          id: 64489,
        },
        {
          name: 'dairy_free',
          id: 64463,
          display_name: 'Dairy-Free',
          type: 'dietary',
        },
        {
          id: 64465,
          display_name: 'Gluten-Free',
          type: 'dietary',
          name: 'gluten_free',
        },
        {
          name: 'healthy',
          id: 64466,
          display_name: 'Healthy',
          type: 'dietary',
        },
        {
          name: 'keto',
          id: 8091756,
          display_name: 'Keto',
          type: 'dietary',
        },
        {
          name: 'pescatarian',
          id: 3801552,
          display_name: 'Pescatarian',
          type: 'dietary',
        },
        {
          name: 'vegan',
          id: 64468,
          display_name: 'Vegan',
          type: 'dietary',
        },
        {
          name: 'vegetarian',
          id: 64469,
          display_name: 'Vegetarian',
          type: 'dietary',
        },
      ],
      approved_at: 1664488873,
      country: 'US',
      language: 'eng',
      sections: [
        {
          components: [
            {
              measurements: [
                {
                  unit: {
                    system: 'none',
                    name: '',
                    display_plural: '',
                    display_singular: '',
                    abbreviation: '',
                  },
                  quantity: '0',
                  id: 709122,
                },
              ],
              raw_text: 'n/a',
              extra_comment: '',
              ingredient: {
                updated_at: 1663791149,
                name: 'A dash of your favorite creators',
                created_at: 1663791149,
                display_plural: 'A dashes of your favorite creators',
                id: 10248,
                display_singular: 'A dash of your favorite creators',
              },
              id: 97184,
              position: 1,
            },
            {
              position: 2,
              measurements: [
                {
                  unit: {
                    name: '',
                    display_plural: '',
                    display_singular: '',
                    abbreviation: '',
                    system: 'none',
                  },
                  quantity: '8',
                  id: 709124,
                },
              ],
              raw_text: 'n/a',
              extra_comment: '',
              ingredient: {
                created_at: 1664488848,
                display_plural: 'ounces viral Tasty classics',
                id: 10346,
                display_singular: 'ounces viral Tasty classic',
                updated_at: 1664488848,
                name: 'ounces viral Tasty classics',
              },
              id: 97185,
            },
            {
              raw_text: '1 package of live cooking demos',
              extra_comment: '',
              ingredient: {
                display_singular: 'live cooking demo',
                updated_at: 1663791304,
                name: 'live cooking demos',
                created_at: 1663791304,
                display_plural: 'live cooking demos',
                id: 10252,
              },
              id: 97181,
              position: 3,
              measurements: [
                {
                  unit: {
                    display_plural: 'packages',
                    display_singular: 'package',
                    abbreviation: 'package',
                    system: 'none',
                    name: 'package',
                  },
                  quantity: '1',
                  id: 709128,
                },
              ],
            },
            {
              extra_comment: '',
              ingredient: {
                display_singular: 'local eat',
                updated_at: 1664488053,
                name: 'local eats',
                created_at: 1664488053,
                display_plural: 'local eats',
                id: 10341,
              },
              id: 97182,
              position: 4,
              measurements: [
                {
                  id: 709127,
                  unit: {
                    abbreviation: 'g',
                    system: 'metric',
                    name: 'gram',
                    display_plural: 'g',
                    display_singular: 'g',
                  },
                  quantity: '285',
                },
                {
                  unit: {
                    name: 'ounce',
                    display_plural: 'oz',
                    display_singular: 'oz',
                    abbreviation: 'oz',
                    system: 'imperial',
                  },
                  quantity: '10',
                  id: 709126,
                },
                {
                  unit: {
                    system: 'none',
                    name: 'can',
                    display_plural: 'cans',
                    display_singular: 'can',
                    abbreviation: 'can',
                  },
                  quantity: '3',
                  id: 709125,
                },
              ],
              raw_text: '3 10-ounce cans of local eats',
            },
            {
              position: 5,
              measurements: [
                {
                  id: 709123,
                  unit: {
                    system: 'none',
                    name: '',
                    display_plural: '',
                    display_singular: '',
                    abbreviation: '',
                  },
                  quantity: '0',
                },
              ],
              raw_text: 'Spicy challenges, to taste',
              extra_comment: 'to taste',
              ingredient: {
                name: 'spicy challenges',
                created_at: 1663791451,
                display_plural: 'spicy challenges',
                id: 10254,
                display_singular: 'spicy challenge',
                updated_at: 1663791451,
              },
              id: 97183,
            },
          ],
          name: null,
          position: 1,
        },
      ],
      draft_status: 'published',
    },
  ],
}

export default samples
